version: '3.8'

services:

  mysql:
    image: mysql:8.0.22
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: cambio
      MYSQL_PASSWORD: cambio123
      MYSQL_ROOT_PASSWORD: cambio123
      MYSQL_DATABASE: cambio_service