server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Antonio06Martins/config-server
          #username: username
          #password: password
          default-label: master
          search-paths:
            - 'greeting-service*'
